# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - /1-Call-MSGraph/
      - /2-Call-OwnApi/
      - /3-Using-KeyVault/
      - /4-Call-OwnApi-Pop/
      - /5-Call-MSGraph-ManagedIdentity/
      - /6-Call-OwnApi-ManagedIdentity/
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "Microsoft.*"
    labels:
      - "dependabot"
      - "dependencies"
